<a href="https://colab.research.google.com/github/Gopalraj-murugesan07/spam-mail-prediction/blob/main/Spam_Mail_Prediction%5BP2%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam Mail Prediction

Ex Span mail : Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005.Text FA to 87121 to receive entry question . iee....Discounts,offers.

Ham mail[Non-Spam mail] : Pls go ahead with watts.I just wanted to be sure.Do have a great weekend.Abiola i.e Personal,Professional.

WORK FLOW

Mail data -----> Data pre processing -----> Train Test split -----> Logistic regression model ----->(new mail) -> Trained Logistic regression model -----> Spam or Ham Prediction.

Importing the Dependencies :

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Collection & Pre-processing

In [ ]:
# loading the data from csv file to a pandas dataframe
raw_mail_data = pd.read_csv('/content/mail_data.csv')

In [ ]:
print(raw_mail_data)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
# checking null values
raw_mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
# if it contains null values
# replace the null values with a null string
mail_data = raw_mail_data.where((pd.notnull(raw_mail_data)),'')

In [ ]:
# printing first 5 rows
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# checking number of rows and columns in the dataframe
mail_data.shape

(5572, 2)

Label Encoding

In [ ]:
# label spam mail as 0 ; ham mail as 1 ;
mail_data.loc[mail_data['Category'] == 'spam','Category',] = 0
mail_data.loc[mail_data['Category'] == 'ham','Category',] = 1

0 ---> Spam

1 ---> ham

In [ ]:
mail_data.head()

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# seperating the data as texts and label

X = mail_data['Message']
Y = mail_data['Category']

In [ ]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

Splitting the data into training and test data

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 3)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(5572,) (4457,) (1115,)

Feature Extraction

In [ ]:
# transform the text data to feature vectors that can be used as input to logistic regression model

feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

# convert Y train and Y test values as integers

Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [ ]:
print(X_train_features)

In [ ]:
print(X_test_features)

Training the Model

Logistic Regresssion

In [ ]:
model = LogisticRegression()

In [ ]:
# training the logistic Regression model with the training data
model.fit(X_train_features,Y_train)

LogisticRegression()

Evaluating the trained model

In [ ]:
# prediction on training data

prediction_on_training_data = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(prediction_on_training_data,Y_train)

In [ ]:
print("Accuracy on training Data : ",accuracy_on_training_data)

Accuracy on training Data :  0.9670181736594121

In [ ]:
# prediction on testing data

prediction_on_test_data = model.predict(X_test_features)
accuracy_on_test_data = accuracy_score(prediction_on_testing_data,Y_test)

In [ ]:
print("Accuracy on test Data : ",accuracy_on_test_data)

Accuracy on test Data :  0.9659192825112107

Building a Predictive System

In [ ]:
input_mail = ["I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times"]

# convert text to feature vectors
input_data_features = feature_extraction.transform(input_mail)

# making prediction
prediction = model.predict(input_data_features)

print(prediction)

if(prediction[0] == 1):
  print('Ham mail')
else:
  print('Spam mail')

[1]
Ham mail

In [ ]:
input_mail = ["WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only."]

# convert text to feature vectors
input_data_features = feature_extraction.transform(input_mail)

# making prediction
prediction = model.predict(input_data_features)

print(prediction)

if(prediction[0] == 1):
  print('Ham mail')
else:
  print('Spam mail')

[0]
Spam mail